# Загрузка данных

In [ ]:
%cd baseline
!wget https://storage.yandexcloud.net/ds-ods/files/files/a49ec917/train.zip
!wget https://storage.yandexcloud.net/ds-ods/files/files/c42aab3c/test.zip
!wget https://storage.yandexcloud.net/ds-ods/files/files/2d9be07b/train.csv

!unzip train.zip
!unzip test.zip

# Подготовка данных для обучения

In [12]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [13]:
train_df = pd.read_csv("../train.csv")
train_df.head()

,file_name,individual_name,label,sequence,side
0,e923dc51c3d3f6ff66ddb56b03f6c535.JPG,0,0,34,right
1,ad168605cf575df7071a8fd3243183d7.JPG,0,0,34,right
2,4c5e1e09c364d17cdce4ae943535e9b9.JPG,0,0,45,right
3,a2347dc80412aaf70f17ff7bdb1b87cb.JPG,0,0,45,right
4,10d51e412312e8b6d28275e201b04a0e.JPG,0,0,45,right

In [14]:
labels = train_df.label.unique()
labels_train, labels_val = train_test_split(labels, test_size=0.25, random_state=42, shuffle=True)

In [15]:
# Добавляем путь к файлам и определяем split
train_df["path"] = "../train/" + train_df["file_name"]
train_df["split"] = np.where(train_df["label"].isin(labels_train), "train", "validation")

# Инициализируем и заполняем столбцы is_query и is_gallery
train_df[["is_query", "is_gallery"]] = np.nan
mask_validation = train_df["split"] == "validation"
train_df.loc[mask_validation, ["is_query", "is_gallery"]] = 1
train_df.head()

,file_name,individual_name,label,sequence,side,path,split,is_query,is_gallery
0,e923dc51c3d3f6ff66ddb56b03f6c535.JPG,0,0,34,right,../train/e923dc51c3d3f6ff66ddb56b03f6c535.JPG,validation,1.0,1.0
1,ad168605cf575df7071a8fd3243183d7.JPG,0,0,34,right,../train/ad168605cf575df7071a8fd3243183d7.JPG,validation,1.0,1.0
2,4c5e1e09c364d17cdce4ae943535e9b9.JPG,0,0,45,right,../train/4c5e1e09c364d17cdce4ae943535e9b9.JPG,validation,1.0,1.0
3,a2347dc80412aaf70f17ff7bdb1b87cb.JPG,0,0,45,right,../train/a2347dc80412aaf70f17ff7bdb1b87cb.JPG,validation,1.0,1.0
4,10d51e412312e8b6d28275e201b04a0e.JPG,0,0,45,right,../train/10d51e412312e8b6d28275e201b04a0e.JPG,validation,1.0,1.0

In [16]:
train_df.to_csv("train_tiger.csv", index=False)